### ISSUE TITLE
Problem in bet on series

### ISSUE THREAD

**Issue by harigyan** [harigyan/Game#10]
When player play on bet on series, then score should be added into the previous score if already launched on same series, on same bet. 
Hint : Similar to battle field launch. 
if already launched on left series 3 : 100 score 
Player again try to launch 200 on left series 3 then total score on left series should be   : 300

**Comment by MishraAarambh** [comment]
*ISSUE*
User cannot bet on series on a single number twice.

*CHANGESET*
Revision No. 19
